### ISSUE TITLE
Week 05 Day 4 - Store Front

### ISSUE THREAD

**Issue by gstark** [AllanSeitz/assignments#19]
In this assignment you will build a mock shopping website in React, with React Router.

## Objectives

* Use components and props effectively in React
* Use React Router to create declarative navigation in your application

## Requirements

In this assignment you will build a mock e-commerce website. Take time to think about the component structure of the page, and create reusable components.

### Explorer Mode

* [x] Your store should have categories that products are placed in.
* [ ] The landing page should display "featured" products.
* [ ] Your store should have a listing page of all products.
* [ ] Your store should have a listing page of products in specific categories (this might be the same component as the previous requirement, think about how this would work).
* [ ] Your store should have a product details page, with a photo, price and other details.
* [ ] Create your own JSON file with data for your products.
* [ ] Create a theme and identity for your store and the products it sells, have fun with this. Take the time to make a nice looking web application for your portfolio.

### Adventure Mode

* [ ] Add enough products to your store that the customer would need multiple pages to browse it all.
* [ ] Add "pagination" to your product listings.

### Epic Mode

* [ ] Build a shopping cart that customers can add items to.
* [ ] Add functionality to manage the quantity of items in the shopping cart.
* [ ] Build a mock (no payment transactions) checkout workflow for the items in a customers shopping cart.

**Comment by AllanSeitz** [comment]
https://github.com/AllanSeitz/storefront.git

Need your help with some of the finishing touches

**Comment by gstark** [comment]
Sure, come see me when you want to review.

**Comment by AllanSeitz** [comment]
https://github.com/AllanSeitz/storefront.git

my top links stopped working not sure why

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
