### ISSUE TITLE
Week 01 Day 2 - Expanding Your World

### ISSUE THREAD

**Issue by gstark** [AllanSeitz/assignments#2]
In this assignment you will end up with a simple styled web page, published on the web.

## Objectives

- Practice using your tools text editor
- Explore new CSS properties
- Publish a web page

## Requirements

- Have `git`, `hub`, and `node` installed. We should have done this together in class.

### Explorer Mode

- [ ] Follow all of the setup instructions (See "Assignment Setup").
- [ ] Using CSS, style your page to imitate some of the classic designs of the web. Feel free to make this look as "bad" as you want. Here are some sites to gain inspiration:
  - [10 90s websites designs you won’t believe existed](https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/)
- [ ] Add a second page about your hobby with (at least) 2 pictures and with other facts about your hobby.
- [ ] Add a menu to the your site so a user can go back and forth between the new pages.
- [ ] Between the 2 pages, use at least 5 tag selectors, 5 id selectors, and 5 class selectors to style content on your page.
- [ ] Deploy your site.

### Adventure Mode

- [ ] use pseudo-classes to style elements when you hover the mouse over them
- [ ] Add a third page, that has a table. Create this table to have alternating colored rows, and a hover over color.
- [ ] Make a nav bar that sticks to the top of the page (see the nav bar here for example: https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
- [ ] Make a footer that always sticks to the bottom of the page

### Epic Mode

- [ ] Explore CSS animations and add some life to your static page. Feel free to really dig into these and try to animated all elements on your page to some extent

### CSS

- https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS

### HTML

- https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags
- http://atozcss.com/start-here/
- http://www.evolutionoftheweb.com

## Reading Material

To prep for tomorrow's lesson, you can [read about flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

**Comment by AllanSeitz** [comment]
STILL WORKING cant edit my class or id tags for some reason. https://github.com/AllanSeitz/hobbies
hobbies-allan.surge.sh

**Comment by AllanSeitz** [comment]
https://github.com/AllanSeitz/hobbies

hobbies-allan.surge.sh

**Comment by gstark** [comment]
Looks great, but your images aren't showing when deployed to `surge`

**Comment by gstark** [comment]
![Awesome Work!](https://media0.giphy.com/media/MSPRmWviscbAY/200w_d.gif)

**Comment by AllanSeitz** [comment]
On Sep 10, 2018, at 8:02 AM, Gavin Stark <notifications@github.com> wrote:—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
