### ISSUE TITLE
Week 07 Day 4 - Wireframes

### ISSUE THREAD

**Issue by gstark** [AllanSeitz/assignments#26]
## Build wireframes of your Capstone Project

# Be prepared to show these to your instructor early next week.

**Comment by AllanSeitz** [comment]
my wireframes were approved

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Get up and dance!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBSdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3323b129c4533d8a45339c345692fab77f9771ac/meets-1.gif)
> &ldquo;Get up and dance!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/61)**__
