### ISSUE TITLE
Week 02 Day 1 - Octodex

### ISSUE THREAD

**Issue by gstark** [AllanSeitz/assignments#4]
GitHub has a great mascot called OctoCat. OctoCat even has it's own gallery of variations, created by GitHub itself and fans, called [Octodex](https://octodex.github.com).

Unfortunately, the Octodex is not responsive\*! Today, your task is to recreate the layout of The Octodex as closely as possible, but make it responsive. You can use all the tools you have at your disposal to get the job done. Use your browser's Developer Tools to inspect their site to find the exact font sizes and padding amounts.

\* Well, _actually_ it uses javascript set the number of columns on page load, but we want to see interactive responsiveness when we resize our window!

## Objectives

- Build on your knowledge of HTML & CSS
- Implement a responsive design with media queries
- Implement, from scratch, a given design
- Understand HTML/CSS Layout
- Be able to place elements on a page where you want them.
- Use flexbox techniques layout pages.

## Requirements

- You should strive to implement the design as close as possible, though, especially if you've never touch HTML or CSS before, this can be extraordinarily difficult, and will take a lot of practice and mileage.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [ ] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors. Download some of your favorite Octocat images to use in your page (12-16 or so). 
- [ ] Use flexbox styles to layout the header and the Octocats (hint: checkout the `flex-wrap` property).
- [ ] use CSS _media queries_ to resize the Octocat containers to look great as a single full-width column on small screens, and a nice grid on bigger screens.
- [ ] watch this video to work more with media queries https://www.youtube.com/watch?v=2KL-z9A56SQ

### Adventure Mode

- [ ] Use several different media queries for small, medium, and large width browsers/devices and make different visual choices for the layout on each.

## Epic Mode

- [ ] Go back to your hobby website, or to the "flexbox" assignment and update site to be mobile friendly and responsive.

**Comment by AllanSeitz** [comment]
https://github.com/AllanSeitz/octo.git
surge ./public --domain octo-allan.surge.sh

**Comment by AllanSeitz** [comment]
i will try and get it working way better, but im ok with where its at

**Comment by AllanSeitz** [comment]
https://github.com/AllanSeitz/octo.git
surge ./public --domain octo-allan.surge.sh

**Comment by gstark** [comment]
The images aren't formatted nice in mobile. I'm going to leave this open for now in case you want to come back and work on it later.

**Comment by AllanSeitz** [comment]
https://github.com/AllanSeitz/octo.git

octo-allan.surge.sh
HOLY COW IT WORKS

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Great job!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBJdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8167037ff2098b5e812290b56d35e1113c17439d/giphy-downsized.gif)
> &ldquo;Great job!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/24)**__
