### ISSUE TITLE
Week 02 Day 2 - Scoreboard

### ISSUE THREAD

**Issue by gstark** [AllanSeitz/assignments#5]
For this assignment you will creating a simple interactive score board for your favorite sport.

## Requirements

Refer to this mockup to design your page:

![](https://suncoast.io/static/scoreboard-b43872ec1befd35514e90e2a116338b0-fb8a0.png)

- A user should be able to update a score and the teams playing.

### Explorer Mode

- [ ] Implement the basic HTML.
- [ ] Implement the basic formatting. Do not worry about styling colors, fonts, etc. yet.
- [ ] Assign click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard coded" value.

### Adventure Mode

- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [ ] Add some styling to make it more presentable. Have fun with it.
- [ ] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add CSS to the winning teams score to indicate who is currently winning.
- [ ] Add anything else that your sport would have on its score board (e.g. fouls, sacks, shots on goal, etc.).
- [ ] Improve the UX to help making score keeping by your sport easier.

**Comment by AllanSeitz** [comment]
https://github.com/AllanSeitz/scoreboard.git
scoreboard-allan.surge.sh
 that was a challenge but i was able to completely redo my CSS and HTML with relative ease. so thats a plus

**Comment by gstark** [comment]
Great work!

**Comment by gstark** [comment]
![Awesome Work!](https://media0.giphy.com/media/1jZ2BzMTZR4Qp4ARW7/200w_d.gif)
